export { LOAD, SAVE } from 'redux-storage'
export const LOCAL_STORAGE_LIFETIME_SET = 'LOCAL_STORAGE_LIFETIME_SET'
export const GET_ITEMS = 'GET_ITEMS'
export const DO_AUTH = 'DO_AUTH'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const RESET = 'RESET'
