export { LOAD, SAVE } from 'redux-storage'
export const LOCAL_STORAGE_LIFETIME_SET = 'LOCAL_STORAGE_LIFETIME_SET'
export const ADD_ITEM = 'ADD_ITEM'
export const FETCH_ITEMS = 'FETCH_ITEMS'
export const DO_AUTH = 'DO_AUTH'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const RESET = 'RESET'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
